### ISSUE TITLE
cc_shoal: unsuitable crontab method and file location

### ISSUE THREAD

**Issue by rptaylor** [cinquo/cloud-init-cern#15]
The cron_shoal property creates a file /etc/crontab_shoal . Then it runs crontab on the file. 
This is an unsuitable place for a cron file, and an inappropriate way of activating the cron job, because it would overwrite any pre-existing crontab file for root.

The cron file location should instead be `/etc/cron.d/shoal-client`   .
The system call to invoke crontab must be removed.
Then the cron job will run automatically because it is in the cron.d directory.

**Comment by cjdcordeiro** [comment]
fixed in fork https://github.com/cjdcordeiro/cloud-init-cern
