### ISSUE TITLE
cc_shoal: change default squids

### ISSUE THREAD

**Issue by rptaylor** [cinquo/cloud-init-cern#16]
The file has some hardcoded squids:

```
'default_squid_proxy': 'http://chrysaor.westgrid.ca:3128;http://cernvm-webfs.atlas-canada.ca:3128;DIRECT'
```

Since default_squid_proxy is configurable via cloud-init, please remove the hard-coded squids, like this:

'default_squid_proxy': 'DIRECT'

Users should define their own squids in their cloud-init scripts.

Thanks!

**Comment by cjdcordeiro** [comment]
fixed in fork https://github.com/cjdcordeiro/cloud-init-cern
