### ISSUE TITLE
cc_shoal: crontab has missing newline character

### ISSUE THREAD

**Issue by rptaylor** [cinquo/cloud-init-cern#17]
The shoal crontab installation does not work.
There should be a newline character at the end of the file:

```
Mon Feb 23 19:40:23 2015: "/etc/crontab_shoal":1: premature EOF
Mon Feb 23 19:40:23 2015: errors in crontab file, can't install.
```

I think this will still be needed regardless of issue #15 .

**Comment by cjdcordeiro** [comment]
fixed in fork https://github.com/cjdcordeiro/cloud-init-cern. New devel release is coming soon
